### PR TITLE
[WIP] Add environment variables documentation to README

### PR DESCRIPTION
**Pull request by andreagrandi**
Note: this PR is a work in progress. Not all the env variables have been properly tested yet. Need to ad example values too.

### CODE REVIEW

**Comment by astagi** [comment]
Remove WIP from the title when it's ready to be merged @andreagrandi .. Thank u :smile:

**Comment by astagi** [comment]
What does it need to be completed @andreagrandi ?

**Comment by andreagrandi** [comment]
@astagi I want to put some example values like I did for WorkshopVenues.

**Comment by astagi** [comment]
Ok no problem @andreagrandi , open another PR for further improvements, I'll merge this one now

**Pull request merged**
