### PR TITLE
Upgrade requirements to Django 1.8.x

### PR DESCRIPTION
**Pull request by andreagrandi**
Note: this is a work in progress

Upgrade requirements to Django 1.8.x and fix python-social-auth version to avoid deprecation warnings.
Unit tests are passing but there are still a few warnings to be fixed.

### CODE REVIEW

**Comment by astagi** [comment]
Fuck you coveralls! :smiling_imp: 

Remove WIP from the title when it's ready to be merged @andreagrandi .. Thank u :smile:

**Comment by astagi** [comment]
Is this still a WIP @andreagrandi ?

**Comment by andreagrandi** [comment]
@astagi I think we need to grab the latest **django-filer** package where the blocking bug has been fixed. So yes, still a work in progress.

**Comment by astagi** [comment]
@andreagrandi unit tests pass and I don't experience any bug with django-filer after some interactive tests. This PR will be merged.

**Pull request merged**
